### PR TITLE
Use gamma angle for roll control

### PR DESCRIPTION
**Pull request by 341101**

### CODE REVIEW

**Comment by Plonq** [comment]
Hi,I haven't tested this yet, but you've removed the `basis` transform in favour of a 'gamma' value (roll), applied after alpha and beta. Applying roll in this way has problems, as I described in this issue: https://github.com/Plonq/bevy_panorbit_camera/issues/41. That's the reason I added the `basis` transform.

You've also removed `allow_upside_down`, which I believe is a mistake. 'upside down' doesn't only apply to the 'roll' axis, it also applies the beta axis. Thus I don't believe adding 'gamma'  limits can replace it.

**Comment by 341101** [comment]
> Hi,I haven't tested this yet, but you've removed the `basis` transform in favour of a 'gamma' value (roll), applied after alpha and beta. Applying roll in this way has problems, as I described in this issue: #41. That's the reason I added the `basis` transform.
> 
> You've also removed `allow_upside_down`, which I believe is a mistake. 'upside down' doesn't only apply to the 'roll' axis, it also applies the beta axis. Thus I don't believe adding 'gamma' limits can replace it.

The original `basis` transform leads to an issue where the rotation axes swap. This occurs if you first roll counterclockwise by 90 degrees, drag the mouse to the right to rotate by 90 degrees, roll counterclockwise again by 90 degrees, drag the mouse down to rotate by 90 degrees, and then move the mouse horizontally. You'll notice that the x and z axes have swapped.
A possible solution to maintain rotation around the local x and y axes when using the `gamma` angle for rolling might be to transform the `delta_angle`.

https://github.com/Plonq/bevy_panorbit_camera/assets/35809384/38ac3cea-5933-408e-879e-24b3f44096be

**Comment by Plonq** [comment]
> The original basis transform leads to an issue where the rotation axes swap.

Hmm, that is a problem. But this PR is IMO worse, as demonstrated in this video. All controls (alpha, beta, and roll) should work as expected at all times. In the video, you can see that as soon as you roll, alpha/beta no longer correspond to left-right/up-down movement.

I mistakenly thought using a separate transform (well, rotation) as the base would solve it, but it evidently has its own problems. Honestly, I would rather not support roll at all than have a weird unintuitive/broken implementation. So let's try and think of a solution that has none of these issues.

https://github.com/Plonq/bevy_panorbit_camera/assets/7709415/f1a5425a-2215-495e-aa5a-035f7405e683

**Comment by Plonq** [comment]
I think there's a fundamental limitation with how this plugin operates that prevents implementing a perfect solution to this. I suspect the problem you've shown with `basis` is due to combining the rotation of the basis with the alpha/beta rotations. As in, adding the alpha/beta rotations 'on top' of the basis rotation doesn't actually result in the expected outcome.

So maybe I was correct in #41 in that this isn't possible with the current implementation. Specifically, we store alpha/beta state and must generate a transform from them.

**Comment by 341101** [comment]
The orbit camera is an `Eulerian rotation` represented by Euler angles, while the rotation with the addition of base Transform to control scrolling is similar to `Local rotation`.
The `Local rotation` is represented by the Google Earth's camera, which has the following rotation code:
``rust
transform.rotate_axis(transform.local_y().into(), self.delta_angle.alpha);
transform.rotate_axis(transform.local_x().into(), -self.delta_angle.beta); transform.rotate_axis(transform.local_x().into(), -self.delta_angle.alpha)
transform.rotate_axis(transform.local_z().into(), self.delta_angle.gamma);
```
The UP direction of this camera is variable, and when the UP direction is locked, the behavior of this camera is similar to an orbit camera without roll
If the orbit camera is to add roll, then I think it would be more appropriate to represent it as a YXZ Eulerian angle, even though it's less intuitive to control.

https://github.com/Plonq/bevy_panorbit_camera/assets/35809384/afc7a38a-af69-45c6-bd60-fffa26e2c3a4

**Comment by Plonq** [comment]
> If the orbit camera is to add roll, then I think it would be more appropriate to represent it as a YXZ Eulerian angle, even though it's less intuitive to control.

Yeah I don't want to do it if it's less intuitive. The video looks like it doesn't have weird gimbal-lock type issues, however the alpha/beta rotation doesn't behave the same. It's no longer a turn-table style orbit camera, it's more free form. There's nothing fundamentally wrong with that, but I am aiming for something more akin to Blender's viewport camera with this plugin.

**Comment by Plonq** [comment]
I appreciate the effort though!

**Pull request closed without merging**
